<%@ Page Language="C#" AutoEventWireup="true" CodeFile="DisableButton.aspx.cs" Inherits="DisableButton" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Disable Button</title>
    <script type="text/javascript">

        function ClientSideClick(myButton) {

            console.log('Submitting Data');

            //  checks client side validation
            //  which is auto-generated by .NET through RequiredFieldValidator server control
            //  If fails, returns false and Submission is aborted
            if (typeof (Page_ClientValidate) == 'function') {
                if (Page_ClientValidate() == false) {
                    return false;
                }
            }

            //  make sure the button is not of type "submit" but "button"
            if (myButton.getAttribute('type') == 'button') {
                //  disable the button to ensure no more clicks are accepted
                myButton.disabled = true;
                myButton.className = "btn-inactive";
                myButton.value = "processing...";              
            }

            // allow submission process to continue to teh server
            return true;

        }
    </script>
    <link href="Content/Style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <form id="form1" runat="server" defaultFocus="TextBox1">
        <div id="outline">
            <asp:Label ID="lblHeader" runat="server" Text="Submit once: disable the button upon submission" CssClass="header" Width="100%"></asp:Label>
            
            <p>&nbsp;</p>

            <table width="300" align="center" cellpadding="2" cellspacing="2">
                <tr>
                    <td align="right">
                        <asp:TextBox ID="TextBox1" runat="server" CssClass="normal-text" Width="100px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="*" ControlToValidate="TextBox1"></asp:RequiredFieldValidator>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="right">
                        <asp:TextBox ID="TextBox2" runat="server" CssClass="normal-text" Width="100px"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="*" ControlToValidate="TextBox2"></asp:RequiredFieldValidator>
                    </td>
                    <td>
                        <asp:Button ID="btnSubmit" runat="server" CssClass="btn-active" Text="Submit Data" OnClientClick="ClientSideClick(this)" UseSubmitBehavior="False" OnClick="btnSubmit_Click" Width="120px" />
                    </td>
                </tr>
            </table>
            <p><asp:Label ID="lblNote" runat="server" CssClass="note-text" Width="100%"></asp:Label></p>
            <p>&nbsp;</p>
            <div class="footer">&nbsp;</div>
        </div>
    </form>
</body>
</html>
